{% set name = "scholarly" %}
{% set version = "1.7.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2c983dd44d9d9398a6f2605102ae6e5586023b41ebbaec1461917ee48eb153f0

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}

  run:
    - arrow
    - beautifulsoup4
    - bibtexparser
    - deprecated
    - fake-useragent
    - free-proxy
    - httpx
    - python >={{ python_min }}
    - python-dotenv
    - PySocks
    - requests
    - selenium
    - sphinx_rtd_theme
    - typing_extensions
    - urllib3

test:
  requires:
    - python {{ python_min }}
  imports:
    - scholarly

about:
  home: https://github.com/scholarly-python-package/scholarly
  license: Unlicense
  license_family: OTHER
  license_file: LICENSE.txt
  summary: Simple access to Google Scholar authors and citations
  doc_url: https://scholarly.readthedocs.io/
  dev_url: https://github.com/scholarly-python-package/scholarly

extra:
  recipe-maintainers:
    - arunkannawadi
